<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKPxOdzj\FileHandler_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKPxOdzj/FileHandler_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKPxOdzj.legacy');

    return;
}

if (!\class_exists(FileHandler_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKPxOdzj\FileHandler_KernelDevDebugContainer::class, FileHandler_KernelDevDebugContainer::class, false);
}

return new \ContainerKPxOdzj\FileHandler_KernelDevDebugContainer([
    'container.build_hash' => 'KPxOdzj',
    'container.build_id' => '3a9929b6',
    'container.build_time' => 1581496134,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKPxOdzj');
