<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6BLFpt4\FileHandler_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6BLFpt4/FileHandler_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6BLFpt4.legacy');

    return;
}

if (!\class_exists(FileHandler_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6BLFpt4\FileHandler_KernelDevDebugContainer::class, FileHandler_KernelDevDebugContainer::class, false);
}

return new \Container6BLFpt4\FileHandler_KernelDevDebugContainer([
    'container.build_hash' => '6BLFpt4',
    'container.build_id' => 'fdc6f336',
    'container.build_time' => 1581491870,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6BLFpt4');
